name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint code
        run: |
          flake8 .

      - name: Check Current Directory
        run: |
          pwd

      - name: Run Tests
        run: |
          PYTHONPATH=. pytest tests/

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials configured"

      - name: Log in to Amazon ECR
        id: ecr-login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 529088267622.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t 529088267622.dkr.ecr.us-east-2.amazonaws.com/ml-api:latest .

      - name: Push Docker image to ECR
        run: |
          docker push 529088267622.dkr.ecr.us-east-2.amazonaws.com/ml-api:latest
